# Generated by Django 4.1 on 2023-08-16 22:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CONFIGURACION', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCientifico', models.CharField(max_length=255, unique=True, verbose_name='Nombre Científico')),
                ('nombreComun', models.CharField(max_length=255, verbose_name='Nombre Común')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='Tecnologias')),
                ('tipoDeEspecie', models.CharField(choices=[('animal', 'animal'), ('vegetal', 'vegetal')], default='animal', max_length=10, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
        migrations.CreateModel(
            name='TipoDeInstitucionCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo De Institución Científica',
                'verbose_name_plural': 'Tipos De Instituciones Científicas',
            },
        ),
        migrations.CreateModel(
            name='TipoDeTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo De Tecnología',
                'verbose_name_plural': 'Tipos De Tecnologías',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='Tecnologias')),
                ('accionEsperada', models.CharField(max_length=255, verbose_name='Acción Esperada')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('especies', models.ManyToManyField(to='INSTITUCIONES_CIENTIFICAS.especie', verbose_name='Especies')),
                ('tipoDeTecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES_CIENTIFICAS.tipodetecnologia', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
            },
        ),
        migrations.CreateModel(
            name='InstitucionCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255, unique=True)),
                ('NombreAbreviado', models.CharField(max_length=255, unique=True, verbose_name='Abreviado')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='InstitucionCientifica')),
                ('Contacto', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Nombre incorrecto', regex='^[a-zA-ZáéíóúÁÉÍÓÚÑñ]+(?:\\s+[a-zA-ZáéíóúÁÉÍÓÚÑñ]+){1,5}$')])),
                ('Telefono', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Teléfono incorrecto', regex='^([+]?53)?\\d{8}$')])),
                ('Correo', models.EmailField(max_length=255)),
                ('Direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('municipio', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='provincia', chained_model_field='provincia', on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.municipio')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.provincia')),
                ('tecnologias', models.ManyToManyField(to='INSTITUCIONES_CIENTIFICAS.tecnologia')),
                ('tipoDeInstitucionCientifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES_CIENTIFICAS.tipodeinstitucioncientifica', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Institución Científica',
                'verbose_name_plural': 'Instituciones Científicas',
            },
        ),
    ]
