# Generated by Django 4.0.2 on 2023-07-29 20:47

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CONFIGURACION', '0001_initial'),
        ('TECNOLOGIAS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeInstitucionCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo De Institución Científica',
                'verbose_name_plural': 'Tipos De Instituciones Científicas',
            },
        ),
        migrations.CreateModel(
            name='InstitucionCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255, unique=True)),
                ('NombreAbreviado', models.CharField(max_length=255, unique=True, verbose_name='Abreviado')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='InstitucionCientifica')),
                ('Contacto', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=255)),
                ('Correo', models.EmailField(max_length=255)),
                ('Direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('municipio', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='provincia', chained_model_field='provincia', on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.municipio')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.provincia')),
                ('tecnologias', models.ManyToManyField(to='TECNOLOGIAS.Tecnologia')),
                ('tipoDeInstitucionCientifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES_CIENTIFICAS.tipodeinstitucioncientifica', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Institución Científica',
                'verbose_name_plural': 'Instituciones Científicas',
            },
        ),
    ]
