# Generated by Django 4.1 on 2023-08-14 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSTITUCIONES_CIENTIFICAS', '0002_institucioncientifica_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodeinstitucioncientifica',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 14, 18, 18, 11, 534198, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipodeinstitucioncientifica',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
