# Generated by Django 4.1 on 2023-07-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_author_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['created']},
        ),
    ]
