# Generated by Django 4.1 on 2023-08-14 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSTITUCIONES_PRODUCTIVAS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucionproductiva',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 14, 15, 16, 13, 630128, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucionproductiva',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 14, 15, 16, 30, 943124, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
