# Generated by Django 4.2 on 2023-08-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INSTITUCIONES_PRODUCTIVAS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucionproductiva',
            name='capacidadDeRefrigeracion',
        ),
    ]
