# Generated by Django 4.1 on 2023-08-15 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSTITUCIONES_PRODUCTIVAS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucionproductiva',
            name='TieneAlamacenConRefrigeracion',
            field=models.BooleanField(default=False, verbose_name='Tiene Refrigeración'),
        ),
        migrations.AddField(
            model_name='institucionproductiva',
            name='capacidadDeProductos',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(limit_value=1, message='La capacidad de productos debe de ser superior a 1 ')]),
        ),
        migrations.AlterField(
            model_name='institucionproductiva',
            name='capacidadDeRefrigeracion',
            field=models.FloatField(verbose_name='Capacidad de refrigeración en KG'),
        ),
    ]
