# Generated by Django 4.1 on 2023-08-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSTITUCIONES_PRODUCTIVAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucionproductiva',
            name='capacidadDeRefrigeracion',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacidad de refrigeración en KG'),
        ),
    ]
