# Generated by Django 4.1 on 2023-08-14 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSTITUCIONES_PRODUCTIVAS', '0002_institucionproductiva_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodeinstitucionproductiva',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 14, 18, 17, 47, 416744, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipodeinstitucionproductiva',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tipodeproducto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 14, 18, 17, 49, 555708, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipodeproducto',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
