# Generated by Django 4.2 on 2023-09-24 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSTITUCIONES_PRODUCTIVAS', '0002_remove_institucionproductiva_capacidadderefrigeracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='institucionProductiva',
        ),
        migrations.AddField(
            model_name='institucionproductiva',
            name='productos',
            field=models.ManyToManyField(to='INSTITUCIONES_PRODUCTIVAS.producto'),
        ),
        migrations.AlterField(
            model_name='institucionproductiva',
            name='Contacto',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Nombre incorrecto', regex='^[a-zA-ZáéíóúÁÉÍÓÚÑñ]+(?:\\s+[a-zA-ZáéíóúÁÉÍÓÚÑñ]+){0,5}$')]),
        ),
    ]
