# Generated by Django 4.2 on 2023-08-21 17:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSitio', models.CharField(max_length=20, null=True, verbose_name='Sitio')),
                ('ImagenLogo', models.ImageField(upload_to='config')),
                ('ImagenBreadcrumbs', models.ImageField(upload_to='config')),
                ('linkFacebook', models.CharField(max_length=255, null=True, verbose_name='Link Facebook')),
                ('linkTwitter', models.CharField(max_length=255, null=True, verbose_name='Link Twitter')),
                ('linkYoutube', models.CharField(max_length=255, null=True, verbose_name='Link Youtube')),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono incorrecto', regex='^([+]?53)?\\d{8}$')])),
                ('direccion', models.CharField(max_length=255, null=True, verbose_name='Dirección')),
                ('horarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración General',
            },
        ),
        migrations.CreateModel(
            name='PaginaPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('Descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Pagina Principal',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('SubTitulo', models.CharField(max_length=255, verbose_name='Sub Título')),
                ('Imagen', models.ImageField(upload_to='Quienes_Somos')),
                ('Descripcion', models.TextField()),
                ('DescripcionNuestroEquipo', models.TextField(verbose_name='Nuestro Equipo')),
            ],
            options={
                'verbose_name': 'Quienes Somos',
                'verbose_name_plural': 'Quienes Somos',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.provincia')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Nombre incorrecto', regex='^[a-zA-ZáéíóúÁÉÍÓÚÑñ]+(?:\\s+[a-zA-ZáéíóúÁÉÍÓÚÑñ]+){1,5}$')])),
                ('Categoria', models.CharField(max_length=255)),
                ('Imagen', models.ImageField(upload_to='Quienes_Somos_Integrantes')),
                ('Descripcion', models.TextField()),
                ('Pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.quienessomos')),
            ],
            options={
                'verbose_name': 'Quienes Somos',
                'verbose_name_plural': 'Quienes Somos',
            },
        ),
        migrations.CreateModel(
            name='Informacion_Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255, unique=True)),
                ('Imagen', models.ImageField(upload_to='Informacion_Principal')),
                ('Descripcion', models.TextField()),
                ('Pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagina_principal_informacion', to='CONFIGURACION.paginaprincipal')),
            ],
            options={
                'verbose_name': 'Información Principal ',
                'verbose_name_plural': 'Informaciones Principales',
            },
        ),
        migrations.CreateModel(
            name='ImagenesFondo_Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='ImagenesFondo_Principal')),
                ('Pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagina_principal_imagenesFondo', to='CONFIGURACION.paginaprincipal')),
            ],
            options={
                'verbose_name': 'Imágen Fondo',
                'verbose_name_plural': 'Imágenes Fondo',
            },
        ),
    ]
