# Generated by Django 4.1 on 2023-07-22 19:12

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('INSTITUCIONES', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.continent')),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionTecnologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255, unique=True)),
                ('NombreAbreviado', models.CharField(max_length=255, unique=True)),
                ('Contacto', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=255)),
                ('Correo', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name': 'Institución Tecnológica',
                'verbose_name_plural': 'Instituciones Tecnológicas',
            },
        ),
        migrations.CreateModel(
            name='TipoDeInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo De Institución',
                'verbose_name_plural': 'Tipos De Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.continent')),
                ('country', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='continent', chained_model_field='continent', on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.country')),
            ],
        ),
    ]
