# Generated by Django 4.1 on 2023-07-22 23:22

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('INSTITUCIONES', '0002_continent_country_instituciontecnologica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCientifico', models.CharField(max_length=255, verbose_name='Nombre Científico')),
                ('nombreComun', models.CharField(max_length=255, verbose_name='Nombre Común')),
                ('tipoDeTecnologia', models.CharField(choices=[('animal', 'animal'), ('vegetal', 'vegetal')], default='animal', max_length=10)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
        migrations.CreateModel(
            name='InstitucionCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255, unique=True)),
                ('NombreAbreviado', models.CharField(max_length=255, unique=True)),
                ('Contacto', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=255)),
                ('Correo', models.EmailField(max_length=255)),
                ('Direccion', models.CharField(max_length=255, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Institución Científica',
                'verbose_name_plural': 'Instituciones Científicas',
            },
        ),
        migrations.CreateModel(
            name='InstitucionProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255, unique=True)),
                ('NombreAbreviado', models.CharField(max_length=255, unique=True)),
                ('Contacto', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=255)),
                ('Correo', models.EmailField(max_length=255)),
                ('Direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('capacidadDeRefrigeracion', models.FloatField(blank=True, verbose_name='Capacidad de refrigeración')),
            ],
            options={
                'verbose_name': 'Institución Productiva',
                'verbose_name_plural': 'Instituciones Productivas',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('institucionProductiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.institucionproductiva')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.municipio')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('accionEsperada', models.CharField(max_length=255, verbose_name='Acción Esperada')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
            },
        ),
        migrations.CreateModel(
            name='TipoDeInstitucionCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo De Institución Científica',
                'verbose_name_plural': 'Tipos De Instituciones Científicas',
            },
        ),
        migrations.CreateModel(
            name='TipoDeInstitucionProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo De Institución Productiva',
                'verbose_name_plural': 'Tipos De Instituciones Productivas',
            },
        ),
        migrations.CreateModel(
            name='TipoDeProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo De Producto',
                'verbose_name_plural': 'Tipos De Productos',
            },
        ),
        migrations.CreateModel(
            name='TipoDeTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo De Tecnología',
                'verbose_name_plural': 'Tipos De Tecnologías',
            },
        ),
        migrations.DeleteModel(
            name='InstitucionTecnologica',
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='tipoDeTecnologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.tipodetecnologia'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipoDeProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.tipodeproducto'),
        ),
        migrations.AddField(
            model_name='institucionproductiva',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='provincia', chained_model_field='provincia', on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.municipio'),
        ),
        migrations.AddField(
            model_name='institucionproductiva',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.provincia'),
        ),
        migrations.AddField(
            model_name='institucionproductiva',
            name='tipoDeInstitucionProductiva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.tipodeinstitucionproductiva'),
        ),
        migrations.AddField(
            model_name='institucioncientifica',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='provincia', chained_model_field='provincia', on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.municipio'),
        ),
        migrations.AddField(
            model_name='institucioncientifica',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.provincia'),
        ),
        migrations.AddField(
            model_name='institucioncientifica',
            name='tecnologias',
            field=models.ManyToManyField(to='INSTITUCIONES.tecnologia'),
        ),
        migrations.AddField(
            model_name='institucioncientifica',
            name='tipoDeInstitucionCientifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.tipodeinstitucioncientifica'),
        ),
        migrations.AddField(
            model_name='especie',
            name='tecnologias',
            field=models.ManyToManyField(to='INSTITUCIONES.tecnologia'),
        ),
    ]
