# Generated by Django 4.1 on 2023-07-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INSTITUCIONES', '0003_especie_institucioncientifica_institucionproductiva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincia',
            name='municipio',
        ),
        migrations.AddField(
            model_name='institucioncientifica',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='InstitucionCientifica'),
        ),
        migrations.AddField(
            model_name='institucionproductiva',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='InstitucionProductiva'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.provincia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Tecnologias'),
        ),
        migrations.AlterField(
            model_name='institucioncientifica',
            name='NombreAbreviado',
            field=models.CharField(max_length=255, unique=True, verbose_name='Abreviado'),
        ),
        migrations.AlterField(
            model_name='institucioncientifica',
            name='tipoDeInstitucionCientifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.tipodeinstitucioncientifica', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='institucionproductiva',
            name='NombreAbreviado',
            field=models.CharField(max_length=255, unique=True, verbose_name='Abreviado'),
        ),
        migrations.AlterField(
            model_name='institucionproductiva',
            name='tipoDeInstitucionProductiva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.tipodeinstitucionproductiva', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipoDeProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.tipodeproducto', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='tipoDeTecnologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSTITUCIONES.tipodetecnologia', verbose_name='Tipo'),
        ),
    ]
