# Generated by Django 4.0.2 on 2023-08-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TECNOLOGIAS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Tecnologias'),
        ),
        migrations.AddField(
            model_name='especie',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
