# Generated by Django 4.1 on 2023-08-14 15:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TECNOLOGIAS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especie',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 14, 15, 15, 40, 869162, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
