# Generated by Django 4.1 on 2023-08-14 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TECNOLOGIAS', '0002_especie_created_especie_modified_tecnologia_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodetecnologia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 14, 18, 17, 4, 264698, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipodetecnologia',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
